config/routes.rb
SugarCube::Application.routes.draw do
  get "home/index"
  root :to => "home#index"

  namespace :admin do
    resources :products
  end

  resources :collections

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :production_collections
  has_many :product, :through => :production_collections
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :description, :status, :multiple_variant, :sale_price, :origin_price,:collection_ids

  has_many :product_collections
  has_many :collections, :through => :product_collections

  
  before_create:initial_status
  
  def status_list
  %w[publish unpublish archive]  
  end
  
  private
  def initial_status
    self.status = "unpublish"
  end
end

app/models/product_collection.rb
class ProductCollection < ActiveRecord::Base
  belongs_to :product
  belongs_to :collection
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
= form_for @product, :url => admin_products_url do |f|
  -if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  -if @product.id
    .field
      = f.label :status
      = f.select :status, @product.status_list

  .field
    = f.label :multiple_variant
    = f.check_box :multiple_variant
  .field
    = f.label :sale_price
    = f.text_field :sale_price
  .field
    = f.label :origin_price
    = f.text_field :origin_price
  .field
    = f.label :collections
    = hidden_field_tag "product[collection_ids][]", nil
    -Collection.all.each do |c|
      = check_box_tag("product[collection_ids][]", c.id, @product.collection_ids.include?(c.id), id:dom_id(c)) 
      = label_tag(dom_id(c), c.title)

  .actions
    = f.submit 'Save'

app/views/admin/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', admin_product_url(@product)
\|
= link_to 'Back', admin_products_url

app/views/admin/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Title
    %th Description
    %th Status
    %th Multiple variant
    %th Sale price
    %th Origin price
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= product.status
      %td= product.multiple_variant
      %td= product.sale_price
      %td= product.origin_price
      %td= link_to 'Show', admin_product_url(product)
      %td= link_to 'Edit', edit_admin_product_url(product)
      %td= link_to 'Destroy', admin_product_url(product), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Product', new_admin_product_url

app/views/admin/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', admin_products_url

app/views/admin/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Description:
  = @product.description
%p
  %b Status:
  = @product.status
%p
  %b Multiple variant:
  = @product.multiple_variant
%p
  %b Sale price:
  = @product.sale_price
%p
  %b Origin price:
  = @product.origin_price

= link_to 'Edit', edit_admin_product_url(@product)
\|
= link_to 'Back', admin_products_url

app/views/collections/_form.html.haml
= form_for @collection do |f|
  -if @collection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@collection.errors.count, "error")} prohibited this collection from being saved:"
      %ul
        - @collection.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/collections/edit.html.haml
%h1 Editing collection

= render 'form'

= link_to 'Show', @collection
\|
= link_to 'Back', collections_path

app/views/collections/index.html.haml
%h1 Listing collections

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @collections.each do |collection|
    %tr
      %td= collection.title
      %td= collection.description
      %td= link_to 'Show', collection
      %td= link_to 'Edit', edit_collection_path(collection)
      %td= link_to 'Destroy', collection, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Collection', new_collection_path

app/views/collections/new.html.haml
%h1 New collection

= render 'form'

= link_to 'Back', collections_path

app/views/collections/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @collection.title
%p
  %b Description:
  = @collection.description

= link_to 'Edit', edit_collection_path(@collection)
\|
= link_to 'Back', collections_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sugar Cube
    = stylesheet_link_tag("application", :media => "all")
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/products/_form.html.haml
= form_for @product do |f|
  -if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  -if @product.id
    .field
      = f.label :status
      = f.select :status, @product.status_list

  .field
    = f.label :multiple_variant
    = f.check_box :multiple_variant
  .field
    = f.label :sale_price
    = f.text_field :sale_price
  .field
    = f.label :origin_price
    = f.text_field :origin_price
  .field
    = f.label :collections
    = hidden_field_tag "product[collection_ids][]", nil
    -Collection.all.each do |c|
      = check_box_tag("product[collection_ids][]", c.id, @product.collection_ids.include?(c.id), id:dom_id(c)) 
      = label_tag(dom_id(c), c.title)

  .actions
    = f.submit 'Save'

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Title
    %th Description
    %th Status
    %th Multiple variant
    %th Sale price
    %th Origin price
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= product.status
      %td= product.multiple_variant
      %td= product.sale_price
      %td= product.origin_price
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Product', new_product_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Description:
  = @product.description
%p
  %b Status:
  = @product.status
%p
  %b Multiple variant:
  = @product.multiple_variant
%p
  %b Sale price:
  = @product.sale_price
%p
  %b Origin price:
  = @product.origin_price

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path